=== 52North/ogcapi-connected-systems/api/part2/openapi/schemas/json/observation.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "datastream@id": {
      "type": "string"
    },
    "foi@id": {
      "type": "string"
    },
    "phenomenonTime": {
      "$ref": "../common/commonDefs.json#/definitions/TimeInstant"
    },
    "resultTime": {
      "$ref": "../common/commonDefs.json#/definitions/TimeInstant"
    },
    "result": {
    }
  },
  "required": [
    "datastream@id", "phenomenonTime", "resultTime", "result"
  ]
}

=== 52North/ogcapi-connected-systems/api/usecases/uxs/observations/saildrone-weather-obs.json
{
  "id": "1h6pmb3ntfmogfppknk9aefpvs",
  "datastream@id": "4e7lckktgdqq",
  "foi@id": "wkigzi6hv817",
  "phenomenonTime": "2022-07-16T20:00:00Z",
  "resultTime": "2022-07-16T20:00:00Z",
  "result": {
    "TEMP_AIR_MEAN": 28.63,
    "BARO_PRES_MEAN": 1013.93,
    "WIND_FROM_MEAN": 84.9,
    "WIND_SPEED_MEAN": 7.01,
    "RH_MEAN": 84.08
  }
}

=== 52North/ogcapi-connected-systems/api/usecases/uxs/observations/saildrone-nav-obs.json
{
  "id": "kpq8a8dt01atfgr5k9pf58a9fs",
  "datastream@id": "ff9g4lkez4ku",
  "foi@id": "o35a8ufrmayt",
  "phenomenonTime": "2019-05-25T00:00:00Z",
  "resultTime": "2019-05-25T00:00:00Z",
  "result": {
    "location": {"lat": 32.3701696, "lon": -64.6955776},
    "SOG": 0.023,
    "COG": 143.6,
    "HDG": 146.0,
    "HDG_WING": 256.7,
    "WING_ANGLE": -84.7,
    "PITCH": -2.3,
    "ROLL": 5.8,
    "STATUS": "-1"
  }
}
